// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvmxWHi1Nn_nLn890KfuXbH1WCRIMn1iQ',
    appId: '1:647324381645:web:4409ecd23715fe8cdf5484',
    messagingSenderId: '647324381645',
    projectId: 'amazing-app-466b9',
    authDomain: 'amazing-app-466b9.firebaseapp.com',
    storageBucket: 'amazing-app-466b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_AALWW2m-Dzmf2UongY3AWTX_QyDK5ow',
    appId: '1:647324381645:android:a51371c9ac404cfddf5484',
    messagingSenderId: '647324381645',
    projectId: 'amazing-app-466b9',
    storageBucket: 'amazing-app-466b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHeu2RhPMrKe7bbNqqzNkJ16yFj-hivU',
    appId: '1:647324381645:ios:1364a64fe0ccd7aedf5484',
    messagingSenderId: '647324381645',
    projectId: 'amazing-app-466b9',
    storageBucket: 'amazing-app-466b9.appspot.com',
    androidClientId: '647324381645-8aj9ktg86lnt19bpn82neki5gk3n1sji.apps.googleusercontent.com',
    iosClientId: '647324381645-aqleak5jqsk3jtdjicn0hhrj4851fs9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazing',
  );

}